//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular2_web_app1.MyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyService.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name GetAppointmentsJSONResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAppointmentsJSON", ReplyAction="*")]
        Angular2_web_app1.MyService.GetAppointmentsJSONResponse GetAppointmentsJSON(Angular2_web_app1.MyService.GetAppointmentsJSONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAppointmentsJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<Angular2_web_app1.MyService.GetAppointmentsJSONResponse> GetAppointmentsJSONAsync(Angular2_web_app1.MyService.GetAppointmentsJSONRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAppointmentsJSONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAppointmentsJSON", Namespace="http://tempuri.org/", Order=0)]
        public Angular2_web_app1.MyService.GetAppointmentsJSONRequestBody Body;
        
        public GetAppointmentsJSONRequest() {
        }
        
        public GetAppointmentsJSONRequest(Angular2_web_app1.MyService.GetAppointmentsJSONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAppointmentsJSONRequestBody {
        
        public GetAppointmentsJSONRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAppointmentsJSONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAppointmentsJSONResponse", Namespace="http://tempuri.org/", Order=0)]
        public Angular2_web_app1.MyService.GetAppointmentsJSONResponseBody Body;
        
        public GetAppointmentsJSONResponse() {
        }
        
        public GetAppointmentsJSONResponse(Angular2_web_app1.MyService.GetAppointmentsJSONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAppointmentsJSONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAppointmentsJSONResult;
        
        public GetAppointmentsJSONResponseBody() {
        }
        
        public GetAppointmentsJSONResponseBody(string GetAppointmentsJSONResult) {
            this.GetAppointmentsJSONResult = GetAppointmentsJSONResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Angular2_web_app1.MyService.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Angular2_web_app1.MyService.WebService1Soap>, Angular2_web_app1.MyService.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Angular2_web_app1.MyService.GetAppointmentsJSONResponse Angular2_web_app1.MyService.WebService1Soap.GetAppointmentsJSON(Angular2_web_app1.MyService.GetAppointmentsJSONRequest request) {
            return base.Channel.GetAppointmentsJSON(request);
        }
        
        public string GetAppointmentsJSON() {
            Angular2_web_app1.MyService.GetAppointmentsJSONRequest inValue = new Angular2_web_app1.MyService.GetAppointmentsJSONRequest();
            inValue.Body = new Angular2_web_app1.MyService.GetAppointmentsJSONRequestBody();
            Angular2_web_app1.MyService.GetAppointmentsJSONResponse retVal = ((Angular2_web_app1.MyService.WebService1Soap)(this)).GetAppointmentsJSON(inValue);
            return retVal.Body.GetAppointmentsJSONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Angular2_web_app1.MyService.GetAppointmentsJSONResponse> Angular2_web_app1.MyService.WebService1Soap.GetAppointmentsJSONAsync(Angular2_web_app1.MyService.GetAppointmentsJSONRequest request) {
            return base.Channel.GetAppointmentsJSONAsync(request);
        }
        
        public System.Threading.Tasks.Task<Angular2_web_app1.MyService.GetAppointmentsJSONResponse> GetAppointmentsJSONAsync() {
            Angular2_web_app1.MyService.GetAppointmentsJSONRequest inValue = new Angular2_web_app1.MyService.GetAppointmentsJSONRequest();
            inValue.Body = new Angular2_web_app1.MyService.GetAppointmentsJSONRequestBody();
            return ((Angular2_web_app1.MyService.WebService1Soap)(this)).GetAppointmentsJSONAsync(inValue);
        }
    }
}
