// <auto-generated />
namespace Calendar.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class restoringcontactstuff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(restoringcontactstuff));
        
        string IMigrationMetadata.Id
        {
            get { return "201705111153553_restoring contact stuff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
